### ISSUE TITLE
Question generation for Disentangled BLIP-VQA? 

### ISSUE THREAD

**Issue by JiahuiKChen** [Karine-Huang/T2I-CompBench#20]
Hi, I'm wondering what model and prompt is used for the question generation part of the Blip-VQA evaluation:

![Screenshot 2024-08-20 at 9 47 06 AM](https://github.com/user-attachments/assets/d34fd283-27d1-4bb6-884d-77b67217946e)

**Comment by Karine-Huang** [comment]
Hello! The question generation is using the package of "Spacy" to extract noun phrases. 
Please find the Line 31-40 in [BLIP_vqa.py](https://github.com/Karine-Huang/T2I-CompBench/blob/main/BLIPvqa_eval/BLIP_vqa.py)
: 
  
        f = file_name.split('_')[0]
        doc = nlp(f)
        
        noun_phrases = []
        for chunk in doc.noun_chunks:
            if chunk.text not in ['top', 'the side', 'the left', 'the right']:  # todo remove some phrases
                noun_phrases.append(chunk.text)
        if(len(noun_phrases)>np_index):
            q_tmp = noun_phrases[np_index]
            image_dict['question']=f'{q_tmp}?'

**Comment by JiahuiKChen** [comment]
Thanks!
