### ISSUE TITLE
Reproduce result for models not supported in diffusers 0.15.0.dev0

### ISSUE THREAD

**Issue by LifuWang-66** [Karine-Huang/T2I-CompBench#21]
Hello!

I want to reproduce the result for Pixart-Alpha, but diffusers 0.15.0.dev0 does not support it. Which version of diffusers should I use? I have tried 0.29.2 but the result is much lower than the values in the report.

**Comment by Karine-Huang** [comment]
Hello~ 
Diffusers 0.15.dev0 is specifically for GORS, is not required for evaluating other models.
For Pixart-α, the authors provided us with a fine-tuned checkpoint version, which we used for evaluation. However, this version of checkpoint is not released to public.

**Comment by LifuWang-66** [comment]
Thanks for your swift response! 

What is the dataset for CLIPScore? Should I use all val.txt in examples/dataset?

**Comment by Karine-Huang** [comment]
Hello, for CLIPScore, you can use the "non-spatial_val.txt".
