### ISSUE TITLE
Question about BLIPvqa code with reproduce scores of shape, texture

### ISSUE THREAD

**Issue by ofzlo** [Karine-Huang/T2I-CompBench#8]
Hi, thank you for sharing your excellent work.

I'm interested in reproducing the B-VQA scores presented in your paper, specifically those in tables 2, 3, and 4. While reviewing the `/BLIPvqa_eval/BLIP_vqa.py` code, I noticed that it primarily uses 'color' as a parameter. I'd like to inquire whether it can be adapted to work with 'shape' and 'texture' as well. Additionally, I'm curious if making this change would have any impact on the score production.

**Comment by Retr0573** [comment]
I'm curious about it too, do you have any understanding now?

**Comment by ofzlo** [comment]
@Retr0573 
I apologize for not being able to provide a more detailed explanation, as it was quite some time ago, but I believe it was not an issue because 'color', 'shape', and 'texture' are using the same JSON file.
